#!/usr/bin/env php

<?php

use Illuminate\Filesystem\Filesystem;
use Mabasic\Kalista\MoveMoviesCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__ . '/vendor/autoload.php'))
{
    // For development purposes
    require __DIR__ . '/vendor/autoload.php';
}
else
{
    // This is important because of bin executable
    require __DIR__ . '/../../autoload.php';
}

$filesystem = new Filesystem();

$app = new Application('Kalista', '2.0.0');

$app->add(new MoveMoviesCommand($filesystem));

$app->run();