#!/usr/bin/env php

<?php

use Illuminate\Filesystem\Filesystem;
use Mabasic\Kalista\Movies\OrganizeCommand as OrganizeMovieCommand;
use Mabasic\Kalista\Movies\RenameCommand as RenameMovieCommand;
use Mabasic\Kalista\TVShows\OrganizeCommand as OrganizeTvShowCommand;
use Mabasic\Kalista\Providers\TheMovieDBServiceProvider;
use Mabasic\Kalista\Services\Environmental\Environmental;
use Mabasic\Kalista\Services\FileBot\FileBot;
use Mabasic\Kalista\Services\TheMovieDB\Movies;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__ . '/vendor/autoload.php'))
{
    // For development purposes
    require __DIR__ . '/vendor/autoload.php';
} else
{
    // This is important because of bin executable
    require __DIR__ . '/../../autoload.php';
}

$app = new Application('Kalista', '0.9.0');

$allowed_extensions = ['avi', 'mp4', 'mkv'];

$filebot = new FileBot;
$filesystem = new Filesystem;

$environmental = new Environmental($filesystem);
$theMovieDBServiceProvider = new TheMovieDBServiceProvider($environmental);
$moviesApi = new Movies($theMovieDBServiceProvider);

// TODO: Remove filebot

$app->add(new OrganizeMovieCommand($allowed_extensions, $filebot, $filesystem, $moviesApi));
$app->add(new RenameMovieCommand($allowed_extensions, $filebot, $filesystem, $moviesApi));

$app->add(new OrganizeTvShowCommand($allowed_extensions, $filebot, $filesystem));

$app->run();