#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/vendor/autoload.php'))
{
    // For development purposes
    require __DIR__.'/vendor/autoload.php';
}
else
{
    // This is important because of bin executable
    require __DIR__.'/../../autoload.php';
}

$app = new Application('Kalista', '0.4.1');

$app->add(new Mabasic\Kalista\Movies\OrganizeCommand(['avi', 'mp4', 'mkv']));

$app->add(new Mabasic\Kalista\TVShows\OrganizeCommand(['avi', 'mp4', 'mkv']));

$app->run();